### ISSUE TITLE
.git的config文件添加了。为啥会出现这个

### ISSUE THREAD

**Issue by xxoo-qx** [764763903a/xdd-plus#103]
![image](https://user-images.githubusercontent.com/34995671/139198244-61dfe939-5c8d-4e45-83b3-32bf789ef995.png)

**Comment by happy-happ** [comment]
你这个是我们这个项目吗，我咋从来没见过这个

**Comment by 2533428814** [comment]
> 你是这个我们这个项目吗，我根本没见过这个
是的呀
![image](https://user-images.githubusercontent.com/34995671/140515409-81323a5b-46d9-44e5-a9f3-fe369070b22a.png)
