### ISSUE TITLE
 同步青龙v2.10.0兼容问题 {"code":400,"message":"Unexpected token \r in JSON at position 15936"}

### ISSUE THREAD

**Issue by xsj684135** [764763903a/xdd-plus#105]
大佬请问是什么原因？昨天还好好的，今天就这样了

**Comment by xsj684135** [comment]
最新进展：
limit为1或11时可上传成功。limit为100或以上时报错
{"code":400,"message":"Unexpected token \n in JSON at position 15965"}

**Comment by hedeqing** [comment]
我也出现这种问题了，我还故意把2.9升级2.10。。。。。。。。现在设置limit好像也没成功

**Comment by hedeqing** [comment]
能解决了，换个数据库就没问题来了，自行恢复数据就好

**Comment by 764763903a** [comment]
升级2.10.2
