### ISSUE TITLE
配置qquid和qqgid后运行xdd会提示解析config.yaml出错

### ISSUE THREAD

**Issue by comwasemo** [764763903a/xdd-plus#111]
配置qquid和qqgid后运行xdd会提示解析config.yaml出错
![IMG_20211105_110750.jpg](https://user-images.githubusercontent.com/85409617/140451842-fcfc0da5-afc3-479c-9f62-a95e3a241ac1.jpg)

**Comment by 764763903a** [comment]
配置缺少空格
