### ISSUE TITLE
更新账号提示wskey

### ISSUE THREAD

**Issue by wqdwang** [764763903a/xdd-plus#126]
> 
![IMG_20211204_110039](https://user-images.githubusercontent.com/55976516/144694589-27ea13cf-eb7a-445d-853b-817a5f48c38f.jpg)
大佬更新账号提示wskey

**Comment by iminiui** [comment]
抓取完wskey不能退出或者切换账号，会秒失效，可以直接清除应用数据

**Comment by 764763903a** [comment]
是的
