### ISSUE TITLE
大佬更新了啥

### ISSUE THREAD

**Issue by guilty-love** [764763903a/xdd-plus#14]
大佬更新了啥，早上我安装好
对了。大佬，CK 也能直接发送给机器人吧

**Comment by foutiu** [comment]
wskey直接提交给机器人也没反应，格式是wskey=xxx;pt_pin=xxx;

**Comment by foutiu** [comment]
还有机器人那些指令也不知道，也没有说明，搞得一脸懵逼

**Comment by guilty-love** [comment]
指令可以到文件中查看



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月8日(星期三) 中午11:47
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [764763903a/xdd-plus] 大佬更新了啥 (#14)





 
还有机器人那些指令也不知道，也没有说明，搞得一脸懵逼
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by foutiu** [comment]
哪一个文件？这个真的不知道

**Comment by foutiu** [comment]
从那些go文件里面看？

**Comment by guilty-love** [comment]
command.go




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月8日(星期三) 中午11:54
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [764763903a/xdd-plus] 大佬更新了啥 (#14)





 
从那些go文件里面看？
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 764763903a** [comment]
马上新增菜单乐

**Comment by 764763903a** [comment]
后面到菜单里面查看

**Comment by foutiu** [comment]
那个wskey要什么格式发送，我就这样发送wskey=xxx;pt_pin=xxx;然后后台发送这样2021/09/08 11:42:05.753 [I] [bot.go:22]，也没有保存起来

**Comment by alal167** [comment]
大佬原本是设置管理账号的master变成登录密码  那想让一个QQ账号导出和查看状态怎么办

**Comment by guilty-love** [comment]
大佬有群或是TG么？





------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "764763903a/xdd-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月8日(星期三) 中午11:56
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [764763903a/xdd-plus] 大佬更新了啥 (#14)





 
马上新增菜单乐
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guilty-love** [comment]
贾维斯J.A.R.V.I.S.  12:25:15
小滴滴开始拉取代码

贾维斯J.A.R.V.I.S.  12:25:15
小滴滴拉取代失败：exit status 128

**Comment by jiujiu-666** [comment]
> 进去到菜单里面查看

大佬，2.9 token问题能解决吗

**Comment by 764763903a** [comment]
> > 进去到菜单里面查看
> 
> 大佬，2.9 token问题能解决吗

排查了 nginx配置问题 多数都是自己拉的青龙仓库 
https://thin-hill-428.notion.site/2-8Faker-QL-pannel-Faker-Repository-environment-Setup-45edcbfe90d74d8abb2d71896eab3be7
请使用官方一键安装  就解决此问题了

**Comment by shuxin8795** [comment]
在go的哪个文件查看机器人指令啊？有点迷糊

**Comment by 764763903a** [comment]
已经新增了菜单了  没有看到的替换reply.php文件，要不就重装把

**Comment by foutiu** [comment]
> 已经新增了菜单了 没有看到的替换reply.php文件，要不就重装把

那个菜单的少了一个点，还有wskey到底应该怎么搞，我就是绑定不了账号，我是这种格式wskey=xxx;pt_pin=xxx;      还是说要什么其他格式才能绑定wskey

**Comment by foutiu** [comment]
> 已经新增了菜单了 没有看到的替换reply.php文件，要不就重装把

重装也没有菜单 ，必须手动修改才行

**Comment by 764763903a** [comment]
> > 已经新增了菜单了 没有看到的替换reply.php文件，要不就重装把
> 
> 重装也没有菜单 ，必须手动修改才行

那是因为指向地址还没改  下个版本就好了

**Comment by foutiu** [comment]
> > > 已经新增了菜单了 没有看到的替换reply.php文件，要不就重装把
> > 
> > 
> > 重装也没有菜单 ，必须手动修改才行
> 
> 那是因为指向地址还没改 下个版本就好了

主要还是怎么导入wskey,我导入一直都没有，后台没数据

**Comment by 764763903a** [comment]
> > > > 已经新增了菜单了 没有看到的替换reply.php文件，要不就重装把
> > > 
> > > 
> > > 重装也没有菜单 ，必须手动修改才行
> > 
> > 
> > 那是因为指向地址还没改 下个版本就好了
> 
> 主要还是怎么导入wskey,我导入一直都没有，后台没数据

pin=xxx;wskey=xxx;
