### ISSUE TITLE
2.9 搞个教程吧 实在是不知道咋搞。。一直获取不到token

### ISSUE THREAD

**Issue by lichen780** [764763903a/xdd-plus#16]
![微信截图_20210908143746](https://user-images.githubusercontent.com/39560327/132458776-4390ffcd-c71d-4841-83b1-b0506ccbcf0b.png)

**Comment by 764763903a** [comment]
加我V  jiayuanwangluo2021 下个向日葵我看看

**Comment by lichen780** [comment]
> 加我V jiayuanwangluo2021 下个向日葵我看看

加了

**Comment by jiujiu-666** [comment]
> > 加我V jiayuanwangluo2021 下个向日葵我看看
> 
> 加了

解决了吗
