### ISSUE TITLE
虚心请教大佬一个问题...

### ISSUE THREAD

**Issue by is-idea** [764763903a/xdd-plus#166]
Emm...我看不懂Go..想知道大佬后台列表里获取的那个 [ 京豆数量, 用户等级, 等级昵称...] 这些数据是怎么拿到的呀?
好人一生平安,感激.

**Comment by zhuanke8** [comment]
https://me-api.jd.com/user_new/info/GetJDUserInfoUnion
仔细看代码就能找到，懂不懂没关系

**Comment by is-idea** [comment]
> [https://api.jd.com/user_newme-getJDInfoUnion](https://me-api.jd.com/user_new/info/GetJDUserInfoUnion) 完全看代码没关系//懂不懂用户关系，找到不懂

学到了,感谢大佬.!

**Comment by is-idea** [comment]
> https://me-api.jd.com/user_new/info/GetJDUserInfoUnion 仔细看代码就能找到，懂不懂没关系

大佬.我有了新问题....
xdd是直接执行的xdd目录下scripts文件夹里的jd_bean_change_new.js脚本吗?
然后拿到返回的文本进行解析然后在推送给绑定了qq的cookie?

如果是的话,我本地并没有node环境,为什么他还能执行成功呢?难道是Go语言的特性???

**Comment by is-idea** [comment]
> > https://me-api.jd.com/user_new/info/GetJDUserInfoUnion 仔细看代码就能找到，懂不懂没关系
> 
> 大佬.我有了新问题.... xdd是直接执行的xdd目录下scripts文件夹里的jd_bean_change_new.js脚本吗? 然后拿到返回的文本进行解析然后在推送给绑定了qq的cookie?
> 
> 如果是的话,我本地并没有node环境,为什么他还能执行成功呢?难道是Go语言的特性???

我看到了....是直接在 asset.go 这个文件里写了很多的post请求去查询的资产信息...并不是去执行js脚本获取的..
