### ISSUE TITLE
使用必看

### ISSUE THREAD

**Issue by 764763903a** [764763903a/xdd-plus#21]
自用、学习、爱用不用。我就是上传数据也不叫偷，我自己脚本还不是想咋写就咋写，整天偷偷偷的，毛病。
##注意事项
 1. master: 的值即为密码，后面不可带注释，全匹配方可登录，也不要pt_pin 可自定义
 2. 2.9+版本需要配置    cid: admin
                  secret: admin
                 在青龙里面系统设置，添加应用后配置
 3.发送wskey即可自动添加账号
 4.账号过期自动换key
 5.定时十二小时自动换key
 6.缓存token
 7.批量绑定wskey
 8.多容器 token缓存过期问题修复
 10.解决%!(EXTRA 错误
11.手动指令更新
12.可替换失效wskey
13wskey失效检测
Whiskey更新
新增删除账号指令
清理过期账号指令
合并详细查询功能

14 找猫咪偷一下CK模糊检测
15 写入失败问题 不知道啥原因
16 wskey失效两次转换
17 wskey过期提示

以上是做完了 以下是待开发

编码问题参考
https://blog.csdn.net/qq_29499107/article/details/83583983
/usr/lib64/python3.6/http

Token故障请先用官方教程重装  已排查是nginx问题
https://thin-hill-428.notion.site/2-8Faker-QL-pannel-Faker-Repository-environment-Setup-45edcbfe90d74d8abb2d71896eab3be7
请使用官方一键安装 就解决此问题了

全面适配新版V4  需要旧版V4的同学自己修改下 container代码 553行
	req := httplib.Post(c.Address + "/api/auth")
	修改为
	req := httplib.Post(c.Address + "/auth")

有问题自己提需求啊。。。有空就解决没空靠自己了各位铁子

**Comment by foutiu** [comment]
发现转换wskey没有用，提示了自动转换还是转换不了

**Comment by 764763903a** [comment]
> 发现转换wskey没有用，提示了自动转换还是转换不了

缺少python3环境

**Comment by foutiu** [comment]
> > 发现转换wskey没有用，提示了自动转换还是转换不了
> 
> 缺少python3环境

安装了python3还是转换不了，之前是2.75的版本，现在使用python3 --version查出来是我安装的3.7.10版本

**Comment by jiujiu-666** [comment]
添加ck显示成功，数据库没有

**Comment by happy-happ** [comment]
> > 发现转换wskey没有用，提示了自动转换还是转换不了
> 
> 缺少python3环境

老哥，我也是这种，linux里安装了，容器里也安装了，就是转换失败

**Comment by foutiu** [comment]
> > > 发现转换wskey没有用，提示了自动转换还是转换不了
> > 
> > 
> > 缺少python3环境
> 
> 老哥，我也是这种，linux里安装了，容器里也安装了，就是转换失败

可能python安装的时候有些问题  开始是pip用不了，后面是sign有问题了

**Comment by xiaopandada** [comment]
> 添加ck显示成功，数据库没有

你是什么版本的py？

**Comment by buse88** [comment]
青龙2.92配置了不生效，青龙的系统设置 应用设置设置好了，拿了cid跟Client Secret填写在conf里面了，不生效

**Comment by buse88** [comment]
更新指定这个命令，wskey失效了，也提示更新成功了，实际更新失败的

**Comment by yongyuanlin** [comment]
能不能配置下A1

**Comment by 764763903a** [comment]
> 更新指定这个命令，wskey失效了，也提示更新成功了，实际更新失败的

修复了 还没提交

**Comment by 764763903a** [comment]
> 青龙2.92配置了不生效，青龙的系统设置 应用设置设置好了，拿了cid跟Client Secret填写在conf里面了，不生效

实际生效的再试试

**Comment by foutiu** [comment]
> > 更新指定这个命令，wskey失效了，也提示更新成功了，实际更新失败的
> 
> 修复了 还没提交

我更新账号一直出现调用sign出错！   这是怎么回事，还有我存入数据库的ck也不能同步进青龙，我用qq机器人导入的也不能存入青龙，只能存在数据库里面

**Comment by jiujiu-666** [comment]
我也是这个问题 ，存入数据库的ck也不能同步进青龙，qq机器人导入的也不能存入青龙，只能存在数据库里面

**Comment by buse88** [comment]
> > 更新指定这个命令，wskey 失效了，也提示更新成功了，实际更新失败的
> 
> 修复了未提交

好的谢谢，丢pin=xxx;wskey=xxx;这样机器人可用自动上传pin跟wskey到面板，但是pt_key不会传，这个可以实现的嘛

**Comment by buse88** [comment]
> > > 更新指定这个命令，wskey失效了，也提示更新成功了，实际更新失败的
> > 
> > 
> > 修复了 还没提交
> 
> 我更新账号一直出现调用sign出错！ 这是怎么回事，还有我存入数据库的ck也不能同步进青龙，我用qq机器人导入的也不能存入青龙，只能存在数据库里面

好的 谢谢

**Comment by Yvan0329** [comment]
可以出一个检测ptkey过期的指令以及屏蔽过期账号吗，青龙通知一直弹，但是xdd没有禁用，发送查询，重启也没有用

**Comment by 764763903a** [comment]
> 可以出一个检测ptkey过期的指令以及屏蔽过期账号吗，青龙通知一直弹，但是xdd没有禁用，发送查询，重启也没有用

已修复 未提交

**Comment by buse88** [comment]
> 可以出一个检测ptkey过期的指令以及屏蔽过期账号吗，青龙通知一直弹，但是xdd没有禁用，发送查询，重启也没有用

这个可以通过设置优先级为负数解决吧，如果不需要也有删除指令可以删除账号的

**Comment by buse88** [comment]
又发现个bug，只要是pin=xxx;wskey=xxx;这种格式的，任意发送账号都会添加成功账号，好像不会检测ck的有效性，

**Comment by buse88** [comment]
又发现个bug，pin前面加一个汉字，上pin=xxx;wskey=xxx;这种格式的，任意发送账号都会添加成功账号进数据库

**Comment by 764763903a** [comment]
> 又发现个bug，pin前面加一个汉字，上pin=xxx;wskey=xxx;这种格式的，任意发送账号都会添加成功账号进数据库


已更新

**Comment by 764763903a** [comment]
> 可以出一个检测ptkey过期的指令以及屏蔽过期账号吗，青龙通知一直弹，但是xdd没有禁用，发送查询，重启也没有用

已更新

**Comment by jiujiu-666** [comment]
> > 可以出一个检测ptkey过期的指令以及屏蔽过期账号吗，青龙通知一直弹，但是xdd没有禁用，发送查询，重启也没有用
> 
> 已更新

大佬，qq机器人导入的ck不能同步到青龙，只能存在数据库里面，这个是什么问题，能解决吗

**Comment by 764763903a** [comment]
> > > 可以出一个检测ptkey过期的指令以及屏蔽过期账号吗，青龙通知一直弹，但是xdd没有禁用，发送查询，重启也没有用
> > 
> > 
> > 已更新
> 
> 大佬，qq机器人导入的ck不能同步到青龙，只能存在数据库里面，这个是什么问题，能解决吗

额。。。那个版本

**Comment by buse88** [comment]
wskey失效了，发送指令  更新指定 还是会提示更新成功，不会提示失败，大佬只修复wskey为空不转换，没修复好wskey失效了还提示成功

**Comment by jiujiu-666** [comment]
> > > > 可以出一个检测ptkey过期的指令以及屏蔽过期账号吗，青龙通知一直弹，但是xdd没有禁用，发送查询，重启也没有用
> > > 
> > > 
> > > 已更新
> > 
> > 
> > 大佬，qq机器人导入的ck不能同步到青龙，只能存在数据库里面，这个是什么问题，能解决吗
> 
> 额。。。那个版本

最新版的

**Comment by 764763903a** [comment]
> wskey失效了，发送指令 更新指定 还是会提示更新成功，不会提示失败，大佬只修复wskey为空不转换，没修复好wskey失效了还提示成功



> wskey失效了，发送指令 更新指定 还是会提示更新成功，不会提示失败，大佬只修复wskey为空不转换，没修复好wskey失效了还提示成功

再更新

**Comment by buse88** [comment]
> > > > > 可以出一个检测ptkey过期的指令以及屏蔽过期账号吗，青龙通知一直弹，但是xdd没有禁用，发送查询，重启也没有用
> > > > 
> > > > 
> > > > 已更新
> > > 
> > > 
> > > 大佬，qq机器人导入的ck不能同步到青龙，只能存在数据库里面，这个是什么问题，能解决吗
> > 
> > 
> > 额。。。那个版本
> 
> 最新版的

我也测试了最新版不能用，容器跟conf都配置好 cid跟secret，后面我换回2.85的版本就能正常使用
