### ISSUE TITLE
最新版 机器人添加ck无法同步青龙，只能存到xdd数据库

### ISSUE THREAD

**Issue by jiujiu-666** [764763903a/xdd-plus#31]

**Comment by lbshr** [comment]
我也是

**Comment by guiyyo** [comment]
我也是，同步不了，青龙版本2.9.2-002

**Comment by 764763903a** [comment]
。。。我也是2.9.2--002 功能正常 错误的请提供日志

**Comment by guiyyo** [comment]
重新创建了个容器重新拉库再试了一遍
看日志看起来好像正常
![image](https://user-images.githubusercontent.com/90620284/133095122-7fa27abd-75e2-45a6-93ce-77376b5542be.png)
但在青龙的环境变量里没有新增。不过在启动的时候会一直弹这个，也不知道是啥问题
![image](https://user-images.githubusercontent.com/90620284/133095161-c963597c-a4a3-458a-9dae-a40881a2ff12.png)

**Comment by 764763903a** [comment]
不正常。。。挂了 你青龙建议重装

**Comment by 764763903a** [comment]
Token故障请先用官方教程重装 已排查是nginx问题
https://thin-hill-428.notion.site/2-8Faker-QL-pannel-Faker-Repository-environment-Setup-45edcbfe90d74d8abb2d71896eab3be7
请使用官方一键安装 就解决此问题了

**Comment by guiyyo** [comment]
已按照你发的链接全部重新装了，还是一样的日志，青龙里还是没有新增

**Comment by 764763903a** [comment]
> 已按照你发的链接全部重新装了，还是一样的日志，青龙里还是没有新增
清理数据库的TOKEN数据

**Comment by 764763903a** [comment]
全部删除 或者把token表删除

**Comment by guiyyo** [comment]
请问下这个数据库在哪儿啊，我找了大半天没找到了

**Comment by guiyyo** [comment]
找到原因了，打开数据库后，token数据是空的，我将青龙token的值复制进去后重新启动xdd，就能同步CK了

**Comment by geqianqianqian** [comment]
> 找到原因了，打开数据库后，token数据是空的，我将青龙token的值复制进去后重启xdd，重新同步CK了

有QQ吗我也是这个问题 想请教一下

**Comment by guiyyo** [comment]
还是有问题，，xdd获取不到token，导致虽然手动复制的可以同步，但只要青龙的token一更新，就没办法同步了，又得重新手动填写一次
