### ISSUE TITLE
清理过期账号不生效

### ISSUE THREAD

**Issue by buse88** [764763903a/xdd-plus#32]
管理员发送指令的，提示如下

删除所有false账号，请慎用

你尚未绑定东账号，请提交wskey，提交后即可查询账户资产信息。

然后没下文了

**Comment by buse88** [comment]
同时青龙v2.9.2-002，配置好了token，ck无法同步到容器，只能在数据库里面

**Comment by 764763903a** [comment]
用删除 1-xxx来完成清理  那个指令我不敢测试 所以有BUG也不去改了

**Comment by 764763903a** [comment]
> 同时青龙v2.9.2-002，配置好了token，ck无法同步到容器，只能在数据库里面

这个问题提供下日志

**Comment by buse88** [comment]
调用sign出错！好像这个出错了，哪个青龙的我删了2.9了哈
