### ISSUE TITLE
中文pin问题

### ISSUE THREAD

**Issue by PJUNYE2** [764763903a/xdd-plus#34]
添加或更新中文pin的账号会导致面板所有CK消失，删除中文pin账号后重启xdd才恢复正常。
xdd和青龙版本为最新。

**Comment by 764763903a** [comment]
pin需要自己转义 抓包出来的也是转义好的pin

**Comment by PJUNYE2** [comment]
向机器人提交的pin就是转义好的

**Comment by PJUNYE2** [comment]
不好意思，我的问题，我发CK没带分号。
我以为CK模糊检测可以连分号都不带。。

**Comment by 764763903a** [comment]
可以不带分号，但是如果走的是旧的格式必须带分号，保留了旧的识别上 加了新的识别

**Comment by 764763903a** [comment]
反正。。如果是抓取的一大堆的不用过滤直接丢就能用

**Comment by PJUNYE2** [comment]
数据库的id能改成按优先级排序吗 或者新增一列账号顺序

**Comment by 764763903a** [comment]
数据库得ID是自增得
