### ISSUE TITLE
如何手动禁用一部分功能？比如自动转换？

### ISSUE THREAD

**Issue by 895450603** [764763903a/xdd-plus#36]

**Comment by 764763903a** [comment]
无wskey得账号不会进行转换。。你无需操心这个问题

**Comment by 895450603** [comment]
> 无wskey得账号不会进行转换。。你无需操心这个问题
大佬你好，感谢你的回复。我有wskey，但是因为青龙已经配置了自动转换，我担心转换的频率过高

**Comment by 764763903a** [comment]
。。。。奥这个问题啊。。。我得意思是 你在我的面板 不要写wskey
我的面板wskey放空就不会转换 我不读青龙的WSKEY配置

**Comment by 895450603** [comment]
哈哈，就是说如果添加了wskey暂时没办法关闭自动转换功能是吧

**Comment by 764763903a** [comment]
。。青龙转换得ptkey并不会反写进入XDD。。 xdd转换的ptkey才会进入青龙 我只能这么说

**Comment by 895450603** [comment]
是的，所以通过xdd写入的ptkey也会通过青龙的自动转换任务，然后xdd那边也会转换，就一天内两个渠道都会转换，觉得次数太多了

**Comment by langhun** [comment]
> 。。。。奥这个问题啊。。。我得意思是 你在我的面板 不要写wskey
> 我的面板wskey放空就不会转换 我不读青龙的WSKEY配置

其实可以把定时转换时间写进config文件。不填就不自动转换。有填写就按填写时间添加任务
config.yaml
#wskey定时转换时间
wskey_to_ptkey_cron: 0 11/12 * * *

cron.go
func initWSPT() {
	c = cron.New()
	if Config.WskeyToPtkeyCron != "" {
		_, err := c.AddFunc(Config.WskeyToPtkeyCron, func() {
			fmt.Println("开始定时自动转换wskey...")
			wskeytoptkey()
		})
		if err != nil {
			logs.Warn("自动转换wskey任务失败：%v", err)
		} else {
			logs.Info("自动转换wskey任务就绪")
		}
	}
	c.Start()
}

**Comment by 764763903a** [comment]
> > 。。。。奥这个问题啊。。。我得意思是 你在我的面板 不要写wskey
> > 我的面板wskey放空就不会转换 我不读青龙的WSKEY配置
> 
> 其实可以把定时转换时间写进config文件。不填就不自动转换。有填写就按填写时间添加任务
> 这也算是多一种选择把。。。
> config.yaml
> #wskey定时转换时间
> wskey_to_ptkey_cron: 0 11/12 * * *
> 
> cron.go
> func initWSPT() {
> c = cron.New()
> if Config.WskeyToPtkeyCron != "" {
> _, err := c.AddFunc(Config.WskeyToPtkeyCron, func() {
> fmt.Println("开始定时自动转换wskey...")
> wskeytoptkey()
> })
> if err != nil {
> logs.Warn("自动转换wskey任务失败：%v", err)
> } else {
> logs.Info("自动转换wskey任务就绪")
> }
> }
> c.Start()
> }

关于这个你可以DIY  但是考虑一下小白的问题 我不想因为改个cron自定义 教一堆人cron表达式怎么写

**Comment by langhun** [comment]
> > > 。。。。奥这个问题啊。。。我得意思是 你在我的面板 不要写wskey
> > > 我的面板wskey放空就不会转换 我不读青龙的WSKEY配置
> > 
> > 
> > 其实可以把定时转换时间写进config文件。不填就不自动转换。有填写就按填写时间添加任务
> > 这也算是多一种选择把。。。
> > config.yaml
> > #wskey定时转换时间
> > wskey_to_ptkey_cron: 0 11/12 * * *
> > cron.go
> > func initWSPT() {
> > c = cron.New()
> > if Config.WskeyToPtkeyCron != "" {
> > _, err := c.AddFunc(Config.WskeyToPtkeyCron, func() {
> > fmt.Println("开始定时自动转换wskey...")
> > wskeytoptkey()
> > })
> > if err != nil {
> > logs.Warn("自动转换wskey任务失败：%v", err)
> > } else {
> > logs.Info("自动转换wskey任务就绪")
> > }
> > }
> > c.Start()
> > }
> 
> 关于这个你可以DIY 但是考虑一下小白的问题 我不想因为改个cron自定义 教一堆人cron表达式怎么写

这也的确是个很头疼的问题。。
我也是改的xdd没放出来，怕头痛

**Comment by 764763903a** [comment]
关注更新吧。。。。因为你的逻辑和我的设计理念有冲突。。。我改了你也可能用不上
