### ISSUE TITLE
升级 提示失败：exit status 1

### ISSUE THREAD

**Issue by yongyuanlin** [764763903a/xdd-plus#39]
升级 提示失败：exit status 1

**Comment by foutiu** [comment]
> 升级 提示失败：exit status 1

xdd目录执行git stash 就可以使用升级，出现
fatal: unable to auto-detect email address (got 'root@iZwz95xdc4z756m9wt4k2rZ.(none)')
Cannot save the current index state
类似的报错执行以下两个命令
git config --global user.email "you@example.com"
git config --global user.name "Your Name"

**Comment by wuyouio** [comment]
> > 升级 提示失败：exit status 1
> 
> xdd目录执行git stash 就可以使用升级，出现
> fatal: unable to auto-detect email address (got 'root@iZwz95xdc4z756m9wt4k2rZ.(none)')
> Cannot save the current index state
> 类似的报错执行以下两个命令
> git config --global user.email "[you@example.com](mailto:you@example.com)"
> git config --global user.name "Your Name"

这个是啥

**Comment by yongyuanlin** [comment]
> > 升级 提示失败：exit status 1
> 
> xdd目录执行git stash 就可以使用升级，出现
> fatal: unable to auto-detect email address (got 'root@iZwz95xdc4z756m9wt4k2rZ.(none)')
> Cannot save the current index state
> 类似的报错执行以下两个命令
> git config --global user.email "[you@example.com](mailto:you@example.com)"
> git config --global user.name "Your Name"

这个是什么

**Comment by foutiu** [comment]
我刚刚就是这样解决的，你看不懂我也没办法

**Comment by foutiu** [comment]
> > > 升级 提示失败：exit status 1
> > 
> > 
> > xdd目录执行git stash 就可以使用升级，出现
> > fatal: unable to auto-detect email address (got 'root@iZwz95xdc4z756m9wt4k2rZ.(none)')
> > Cannot save the current index state
> > 类似的报错执行以下两个命令
> > git config --global user.email "[you@example.com](mailto:you@example.com)"
> > git config --global user.name "Your Name"
> 
> 这个是什么

这个也就是shell进入xdd目录执行那些命令就行了，名字中间替换你自己的信息，不懂可以自行百度查那些命令是什么意思

**Comment by 764763903a** [comment]
在目录下进行git pull 发生任何错误可以百度

**Comment by ddd-zero** [comment]
刚刚解决了
exit status 1
git: 'remote-https' is not a git command. See 'git --help'.
安装一下 git-http 就好了。我不知道你们用的什么库管理装的git。我用的opkg
--------------------
exit status 128报错是git不是64位版本，更新一下最新版的git就好了
