### ISSUE TITLE
调用sign出错

### ISSUE THREAD

**Issue by kekity** [764763903a/xdd-plus#40]
![image](https://user-images.githubusercontent.com/28950348/133258317-9620cf52-a318-450a-99c5-ce0213096dd2.png)
这个是为什么呢

**Comment by 764763903a** [comment]
铁子咋解决的  给个教程吧。。。一堆人问我

**Comment by kekity** [comment]
> 铁子咋解决的 给个教程吧。。。一堆人问我

没解决。。。getsign返回None，不懂

**Comment by 764763903a** [comment]
看看有没有人解决再喊你
