### ISSUE TITLE
wskey转换超时

### ISSUE THREAD

**Issue by luyunsheng666** [764763903a/xdd-plus#43]
大佬 转换超时怎么解决呀

**Comment by siyue666** [comment]
我之前也是转换超时，看看有没有安装python3环境和pip3模块，yum install python3 && pip3 install requests

**Comment by luyunsheng666** [comment]
好了 谢谢大佬指点&nbsp; 感谢感谢




------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "764763903a/xdd-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月15日(星期三) 中午12:42
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [764763903a/xdd-plus] wskey转换超时 (#43)





 
我之前也是转换超时，看看有没有安装python3环境和pip3模块，yum install python3 &amp;&amp; pip3 install requests
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 764763903a** [comment]
解决就行

**Comment by chern91552** [comment]
怎么解决的

**Comment by luyunsheng666** [comment]
yum install python3 &amp;&amp; pip3 install requests




一位社会不知名大佬给我的教程&nbsp; 很管用


------------------&nbsp;原始邮件&nbsp;------------------
发件人:                                                                                                                        "764763903a/xdd-plus"                                                                                    ***@***.***&gt;;
发送时间:&nbsp;2021年9月16日(星期四) 上午8:34
***@***.***&gt;;
***@***.******@***.***&gt;;
主题:&nbsp;Re: [764763903a/xdd-plus] wskey转换超时 (#43)





 
怎么解决的
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 1987980421** [comment]
怎么解决的

**Comment by luyunsheng666** [comment]
> 怎么解决的

看上面记录啊

**Comment by 1987980421** [comment]
-bash: syntax error near unexpected token `;&'提示语法错误
