### ISSUE TITLE
大佬，我进到后面能看到CK和WSKEY

### ISSUE THREAD

**Issue by guilty-love** [764763903a/xdd-plus#45]
大佬，
之前的时候，我在青龙面板中都是手动增加ck和wskey,
可刚刚我发现青龙中的CK全给删除了，但是WSKEY还是在里面的，
我进到XDD后面能看到CK和WSKEY也是存在的。这是啥情况啊，XDD不能把CK传递给青龙么？刚刚发生的问题，之前能自动增加到青龙中。是不是要更新下WSKEY?

可CK怎么传递到青龙中呢？

**Comment by 764763903a** [comment]
额 xdd是会自动写入青龙的

**Comment by guilty-love** [comment]
关键是青龙中只留 下了WSKEY是没有转换的，
CK一个也没有。

**Comment by 764763903a** [comment]
我找到问题了立马修复

**Comment by guilty-love** [comment]
辛苦，辛苦，大佬，还有，希望能够增加手动指定是否需要转换WSKEY，因为我有单独下载转换的JS，

**Comment by 764763903a** [comment]
。。。。一直都能手动指定

**Comment by guilty-love** [comment]
囧。是那个时间设置么？不想让自动更新



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月15日(星期三) 晚上11:39
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [764763903a/xdd-plus] 大佬，我进到后面能看到CK和WSKEY (#45)





 
。。。。一直都能手动指定
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guilty-love** [comment]
坐等大佬更新。。。。

**Comment by guilty-love** [comment]
大佬。昨天 晚上更新后，CK能传递到青龙中了，然后早上一醒我就又去看，确实是存在稳定的，今天早上还有人增加了。也是增加到了CK中，但是刚刚我重启了服务器，发现青龙中CK全消失了，只留 下了WSKEY，但是在XDD后面看。里面的全都存在

**Comment by 764763903a** [comment]
> 大佬。昨天 晚上更新后，CK能传递到青龙中了，然后早上一醒我就又去看，确实是存在稳定的，今天早上还有人增加了。也是增加到了CK中，但是刚刚我重启了服务器，发现青龙中CK全消失了，只留 下了WSKEY，但是在XDD后面看。里面的全都存在

因为我修复得版本都没推送呢

**Comment by 764763903a** [comment]
> > 大佬。昨天 晚上更新后，CK能传递到青龙中了，然后早上一醒我就又去看，确实是存在稳定的，今天早上还有人增加了。也是增加到了CK中，但是刚刚我重启了服务器，发现青龙中CK全消失了，只留 下了WSKEY，但是在XDD后面看。里面的全都存在
> 
> 因为我修复得版本都没推送呢

现在更新最新版 然后把里面nickname为空白的账号查询一遍就好了

**Comment by guilty-love** [comment]
.....晕倒。~~~




------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 上午10:04
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [764763903a/xdd-plus] 大佬，我进到后面能看到CK和WSKEY (#45)





  
大佬。昨天 晚上更新后，CK能传递到青龙中了，然后早上一醒我就又去看，确实是存在稳定的，今天早上还有人增加了。也是增加到了CK中，但是刚刚我重启了服务器，发现青龙中CK全消失了，只留 下了WSKEY，但是在XDD后面看。里面的全都存在
  
因为我修复得版本都没推送呢
 
&mdash;
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guilty-love** [comment]
现在后台里面我把空白的帐号全删除了，只留 下了有名字的，
现在还要做什么么？因为我在青龙中看到并没有同步，因为在XDD后面看到的有青龙中并没有
是不是需要给机器人输入什么指令？大佬

**Comment by guilty-love** [comment]
好难过，青龙重新安装了~~好像也不传递进去，
对了发现个大bug&nbsp; admin.html这个页面的登录密码不区分大小写，设置了大小写混合密码，实际使用中，随便全大写或小写都能进入，只要别打错字


 
---原始邮件---
发件人: ***@***.***&gt;
发送时间: 2021年9月16日 10:05:26
收件人: ***@***.***&gt;;
抄送: ***@***.******@***.***&gt;;
主题: Re: [764763903a/xdd-plus] 大佬，我进到后面能看到CK和WSKEY (#45)




   
大佬。昨天 晚上更新后，CK能传递到青龙中了，然后早上一醒我就又去看，确实是存在稳定的，今天早上还有人增加了。也是增加到了CK中，但是刚刚我重启了服务器，发现青龙中CK全消失了，只留 下了WSKEY，但是在XDD后面看。里面的全都存在
  
因为我修复得版本都没推送呢
  
现在更新最新版 然后把里面nickname为空白的账号查询一遍就好了
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by guilty-love** [comment]
我是不是操作错了啊，大佬。我这里就不传递CK，青龙是2.9.2-002版本，
青龙也重新安装 了，XDD也是重新编译安装好了
配置文件如下，


mode: parallel
containers:
  - address: http://192.168.218.177:5700
    username: admin
    password: jxxxxxxx
    cid: F-P4V_xxn3
    secret: LjE8_cxTXlDxxxoClq3aS7G
    weigth:  
    mode: parallel
    limit: 9999
AtTime:  #填写1-12之间的数  填错自负默认为10  10点容易出现高峰超时。
IsHelp:   #填写true或者false  false
IsOldV4: #填写true或者false  false是否新版或者旧版V4
theme:  ./theme/admin.html
static: ./static
master: Jxxxxxxxx
database:  
qywx_key:
daily_push:
resident:
user_agent:
telegram_bot_token:
telegram_user_id:
qquid: 973264
qqgid: 985299077
qbot_public_mode: true
default_priority:
no_ghproxy: true
daily_asset_push_cron:
repos:
  - git:

**Comment by 764763903a** [comment]
群里问问
