### ISSUE TITLE
plus登陆页面 ---会员中心给你们看个样板图把

### ISSUE THREAD

**Issue by guilty-love** [764763903a/xdd-plus#49]
加油。希望增加页面中手动输入CK的功能。大佬加油

**Comment by 764763903a** [comment]
写完了 会员中心还没对接

**Comment by guilty-love** [comment]
大佬。。。。又出现昨天 晚上的情况了，我现在青龙中只有WSkey,一个CK也没有啦



------------------&nbsp;原始邮件&nbsp;------------------
发件人: ***@***.***&gt;; 
发送时间: 2021年9月16日(星期四) 上午9:55
收件人: ***@***.***&gt;; 
抄送: ***@***.***&gt;; ***@***.***&gt;; 
主题: Re: [764763903a/xdd-plus] plus登陆页面 ---会员中心给你们看个样板图把 (#49)





 
写完了 会员中心还没对接
 
—
You are receiving this because you authored the thread.
Reply to this email directly, view it on GitHub, or unsubscribe.
Triage notifications on the go with GitHub Mobile for iOS or Android.

**Comment by 764763903a** [comment]
明后两天出八
