### ISSUE TITLE
CookieOK这个方法有问题

### ISSUE THREAD

**Issue by Yvan0329** [764763903a/xdd-plus#53]
available.go文件的CookieOK这个方法，获取账号信息https://me-api.jd.com/user_new/info/GetJDUserInfoUnion
这个没有返回，所以都没更新账号信息，也没有进行账号失效的操作。应该是个bug

**Comment by 764763903a** [comment]
是吗。。。。我没注意 收到 发烧两天刚看到

**Comment by Yvan0329** [comment]
> 是吗。。。。我没注意 收到 发烧两天刚看到

大佬辛苦了，京东会返回空数据，导致拉取不到数据，然后校验不了cookie有效性，其他大佬有个库，貌似可以解决这个问题，附上链接：https://github.com/ccwav/QLScript/blob/main/jd_CheckCK.js，貌似集成这个，可以解决pt_pin过期或者无效了，不会自动禁用账号，也能发送通知给指定qq和管理员。

**Comment by PJUNYE2** [comment]
大佬参考一下sillyGirl的京东拓展库 https://github.com/ufuckee/jd_cookie
这个我试了能正常检测，有一个号在xdd查询功能没有用户信息和京豆数，这拓展也能识别。

**Comment by 764763903a** [comment]
收到

**Comment by 764763903a** [comment]
。。我看了写的是一样的
