### ISSUE TITLE
账号失效无提醒

### ISSUE THREAD

**Issue by PJUNYE2** [764763903a/xdd-plus#54]
账号失效无提醒，也没有从面板中移除

**Comment by Yvan0329** [comment]
同

**Comment by happy-happ** [comment]
账号失效有提醒啊，机器人会发送管理和绑定qq

**Comment by 764763903a** [comment]
Ck失效还是wskey失效

**Comment by 764763903a** [comment]
已修复

**Comment by PJUNYE2** [comment]
账号昵称：jd_693f2191756e4
用户等级：56
等级名称：铜牌用户
京豆数据异常
当前京豆：3385京豆
暂无红包数据🧧
东东农场：数据异常
东东萌宠：数据异常
极速金币：0(≈0.00元)
京东赚赚：暂无数据
京东秒杀：暂无数据
推一推券：无优惠券
惊喜牧场：0枚鸡蛋

ck失效 数据库 可用显示true
