### ISSUE TITLE
大佬，有打算实现不用加机器人qq也能和机器人私聊交互吗

### ISSUE THREAD

**Issue by a131656** [764763903a/xdd-plus#56]
这样就不用老是要登机器人qq同意别人的好友添加请求了0.0

**Comment by happy-happ** [comment]
> 这样就不用老是要登机器人qq同意别人的好友添加请求了0.0

可以，可以不加机器人好友，但是群要开启私聊功能

**Comment by chern91552** [comment]
> > 这样就不用老是要登机器人qq同意别人的好友添加请求了0.0
> 
> 可以，可以不加机器人好友，但是群要开启私聊功能

希望添加有好友请求自动通过的功能。
之前使用xdd的时候发现如果小号设置成允许任何人添加好友，别人给小号能发消息但是小号不会自动回复

**Comment by a131656** [comment]
> > > 这样就不用了是要登机器人qq同意别人的好友添加请求了0.0
> > 
> > 
> > 可以，可以不加机器人好友，但群要开启私聊功能
> 
> 希望添加有好友请求自动通过的功能。
> 之前使用xdd的时候会发现如果小号设置成允许任何人添加，别人给小号能发消息但是小号不会自动回复

大佬牛逼

**Comment by 764763903a** [comment]
已实现
