### ISSUE TITLE
青龙内的应用是随意填写么？还是有什么格式或固定的值？

### ISSUE THREAD

**Issue by guilty-love** [764763903a/xdd-plus#6]
青龙内的应用是随意填写么？还是有什么格式或固定的值？

**Comment by 764763903a** [comment]
随意

**Comment by guilty-love** [comment]
感谢。回复好快~~~我在青龙内新建应用后，有二个Client ID | Client Secret 值。他是自动生成的出来且不让修改，我看你说明文档写的要改成admin。这咋回事

**Comment by 764763903a** [comment]
。。。那个是一个默认值你改掉就行乐。。。我总不能写我自己的值把
