### ISSUE TITLE
一个和短信登陆对接的bug

### ISSUE THREAD

**Issue by 8827974** [764763903a/xdd-plus#66]
xdd账号管理里面qq栏如果有数字的话{也就是说不是全是0的情况下}，短信登陆的账号不会同步到xdd，可以到青龙
![图片](https://user-images.githubusercontent.com/77087225/134761115-3a0bce14-7db6-4b34-9069-650291387d6b.png)

**Comment by 764763903a** [comment]
tg私聊我 建议你上傻妞魔改版
