### ISSUE TITLE
青龙2.9的 在机器人提交的ck不同步到青龙吗？

### ISSUE THREAD

**Issue by lichen780** [764763903a/xdd-plus#7]
青龙2.9的 在机器人提交的ck不同步到青龙吗？ 还有就是 这菜单功能是呼出关键词是啥啊。。。

**Comment by lichen780** [comment]
现在管理后台怎么进  我设置的端口好像没用。。打不开 端口也开放了的

**Comment by lichen780** [comment]
麻烦大佬顺便添加下wskey 和ptkey 两个的模糊匹配

**Comment by 764763903a** [comment]
默认主题可以进

**Comment by lichen780** [comment]
> 默认主题可以进

2.9的不能同步到青龙吗？ck

**Comment by 764763903a** [comment]
可以啊

**Comment by lichen780** [comment]
> 可以啊

我这边没同步成功。。
而且看日志是不是就会出现下面这些字符
2021/09/07 16:13:57 /www/wwwroot/xdd/xdd/models/db.go:328
[0.167ms] [rows:1] SELECT * FROM `tokens` WHERE Address = "http://ip:端口" ORDER BY expiration desc,`tokens`.`expiration` LIMIT 1
2021/09/07 16:13:57.247 [I] [container.go:469]  缓存token

2021/09/07 16:13:57.247 [I] [container.go:469]  2021-08-12 16:13:57.247011677 +0800 CST m=-2246374.196551307

2021/09/07 16:13:57.247 [I] [container.go:469]  2021-09-07 00:00:00 +0800 +0800

2021/09/07 16:13:57.247 [I] [container.go:469]  获取缓存成功

**Comment by lichen780** [comment]
后台删除账户居然删除不了。。

**Comment by jiujiu-666** [comment]
我也是，ck没同步青龙2.9

**Comment by lichen780** [comment]
> 我也是，ck没同步青龙2.9

知道机器人呼出菜单的指令吗？

**Comment by lichen780** [comment]
时不时就会出现这样的日志

```
2021/09/07 17:13:58.357 [D] [container.go:469]  <nil>


2021/09/07 17:13:58 /www/wwwroot/xdd/xdd/models/db.go:328
[0.182ms] [rows:1] SELECT * FROM `tokens` WHERE Address = "http://IP:端口" ORDER BY expiration desc,`tokens`.`expiration` LIMIT 1
2021/09/07 17:13:58.357 [I] [container.go:469]  缓存token

2021/09/07 17:13:58.357 [I] [container.go:469]  2021-08-12 17:13:58.357350628 +0800 CST m=-2242773.086212356

2021/09/07 17:13:58.357 [I] [container.go:469]  2021-09-07 00:00:00 +0800 +0800

2021/09/07 17:13:58.357 [I] [container.go:469]  获取缓存成功

2021/09/07 17:13:58.424 [W] [container.go:169]  <html>
<head><title>405 Not Allowed</title></head>
<body>
<center><h1>405 Not Allowed</h1></center>
<hr><center>nginx</center>
</body>
</html>

```

**Comment by 764763903a** [comment]
config配置错误

**Comment by lichen780** [comment]
> config配置错误

对了的吧   也配置了二次验证的参数值的

**Comment by 764763903a** [comment]
2.9 启用cid security  弃用username和password

**Comment by lichen780** [comment]
> 2.9 启用cid security 弃用username和password

这两我都设置了的..

**Comment by lichen780** [comment]
> 2.9 启用cid security 弃用username和password

只设置 cid security还是同步不了

**Comment by 764763903a** [comment]
旧的数据库请清除token数据要不然就删除 删除xdd.db

**Comment by 764763903a** [comment]
> ![image](https://user-images.githubusercontent.com/82791035/132431765-5d42b6b2-dc26-47e8-8c93-2478dfc7e309.png)
> 新建的数据库也没用

外网地址自己调试nginx  地址最好写内网 127.0.0.1
