### ISSUE TITLE
QQ私信机器人发wskey，没有任何提示也不绑定QQ号码

### ISSUE THREAD

**Issue by Joy-yuhuan** [764763903a/xdd-plus#9]
再次交期的时候显示重复写入，但是第一次的时候没反应。也不绑定提交者QQ号（管理员提交好像可以绑定管理员QQ）

**Comment by 764763903a** [comment]
听不懂。已经有人加了绑定指令乐

**Comment by Joy-yuhuan** [comment]
是最新的吗？我昨天用让朋友发送wskey给机器人，第一次发送没反应，然后再发送显示重复写入了。然后再发送查询给机器人回复未绑定QQ信息。去后台面板看也发现没没绑定QQ信息，我手动加上去后可以了

**Comment by 764763903a** [comment]
这个问题我知道 晚点会解决 添加失败多发两次就好了

**Comment by 764763903a** [comment]
已经添加 wskey绑定QQ
